name: Underground
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  flutter_svg: any
  http: any
  photo_view: any
  flutter_range_slider: any
  font_awesome_flutter: any
  flutter_tindercard: any
  cached_network_image: any
  scrolling_page_indicator: any
  page_transition: any
  google_maps_flutter: any

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_launcher_icons: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/
    - images/navBar/
    - images/text_field/
    - images/icon/

  uses-material-design: true

  fonts:
    - family: Black
      fonts:
        - asset: fonts/TTFirsNeue-Black.ttf
    - family: Bold
      fonts:
        - asset: fonts/TTFirsNeue-Bold.ttf
    - family: DemiBold
      fonts:
        - asset: fonts/TTFirsNeue-DemiBold.ttf
    - family: ExtraBold
      fonts:
        - asset: fonts/TTFirsNeue-ExtraBold.ttf
    - family: ExtraLight
      fonts:
        - asset: fonts/TTFirsNeue-ExtraLight.ttf
    - family: Medium
      fonts:
        - asset: fonts/TTFirsNeue-Medium.ttf
    - family: Regular
      fonts:
        - asset: fonts/TTFirsNeue-Regular.ttf
    - family: Thin
      fonts:
        - asset: fonts/TTFirsNeue-Thin.ttf
    - family: Light
      fonts:
        - asset: fonts/TTFirsNeue-Light.ttf

flutter_icons:
  android: true
  ios: false
  image_path: "images/icon/icon.png"
  adaptive_icon_background: "images/icon/icon-bg.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "images/icon/icon-fg.png" # only available for Android 8.0 devices and above
